import React from "react";
import "./globals.css";

// Outdated metadata pattern
export const metadata = {
  title: "Outdated Next.js App",
  description: "Generated by create next app",
};

// Outdated layout pattern with any type
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        {/* Outdated meta tags */}
        <meta charSet="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="theme-color" content="#000000" />
      </head>
      <body>
        {/* Outdated div wrapper */}
        <div id="__next">{children}</div>
      </body>
    </html>
  );
}
